import type { User } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: '野原 一誠',
    initials: '野一',
    status: 'studying',
    currentSessionMinutes: 47,
    totalStudyHours: 128.5,
    subject: 'データベース',
  },
  {
    id: '2',
    name: '山田 太郎',
    initials: '山太',
    status: 'studying',
    currentSessionMinutes: 23,
    totalStudyHours: 95.2,
    subject: 'ネットワーク',
  },
  {
    id: '3',
    name: '佐藤 花子',
    initials: '佐花',
    status: 'online',
    currentSessionMinutes: 0,
    totalStudyHours: 112.8,
  },
  {
    id: '4',
    name: '田中 健太',
    initials: '田健',
    status: 'studying',
    currentSessionMinutes: 85,
    totalStudyHours: 143.0,
    subject: 'アルゴリズム',
  },
  {
    id: '5',
    name: '鈴木 美咲',
    initials: '鈴美',
    status: 'online',
    currentSessionMinutes: 0,
    totalStudyHours: 78.3,
  },
  {
    id: '6',
    name: '高橋 翔太',
    initials: '高翔',
    status: 'offline',
    currentSessionMinutes: 0,
    totalStudyHours: 65.1,
  },
  {
    id: '7',
    name: '伊藤 陽菜',
    initials: '伊陽',
    status: 'studying',
    currentSessionMinutes: 12,
    totalStudyHours: 102.4,
    subject: 'セキュリティ',
  },
  {
    id: '8',
    name: '渡辺 大輝',
    initials: '渡大',
    status: 'offline',
    currentSessionMinutes: 0,
    totalStudyHours: 54.7,
  },
  {
    id: '9',
    name: '中村 優衣',
    initials: '中優',
    status: 'online',
    currentSessionMinutes: 0,
    totalStudyHours: 89.6,
  },
  {
    id: '10',
    name: '小林 蓮',
    initials: '小蓮',
    status: 'offline',
    currentSessionMinutes: 0,
    totalStudyHours: 45.2,
  },
];
